Contacts:
    type: entity
    table: contacts
    id:
        id:
            type: integer
            nullable: true
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: last_name
        streetNumber:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: street_number
        street:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        city:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        country:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        phoneNumber:
            type: string
            nullable: false
            length: 25
            options:
                fixed: false
            column: phone_number
        birthDate:
            type: date
            nullable: false
            column: birth_date
        email:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        profilePicture:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: profile_picture
        createdDate:
            type: datetime
            nullable: true
            column: created_date
        updatedDate:
            type: datetime
            nullable: true
            column: updated_date
    lifecycleCallbacks: {  }
